version: '3'  # Версия Docker Compose

services:
  # Сервис для Node.js приложения
  nodejs-app:
    build:
      context: .
      dockerfile: Dockerfile  # Путь к вашему Dockerfile для Node.js приложения
      args:
        - SOURCE_DIR=node-js-getting-started
    environment:
      - DB_CONNECT=testdb  # Переменные окружения для Node.js приложения
      - PORT=3000
    ports:
      - "5001:5001"  # Проксируем порт 5001 из контейнера на порт 3000 хост-системы
    depends_on:
      - postgres-db  # Зависимость от сервиса PostgreSQL
      - elasticsearch  # Зависимость от сервиса Elasticsearch

  # Сервис для PostgreSQL базы данных
  postgres-db:
    image: postgres:latest  # Используем официальный образ PostgreSQL

  # Сервис для Elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.4  # Используем официальный образ Elasticsearch

volumes:
  nodejs-app-data:  # Том для данных Node.js приложения (если необходимо)


